# Generated by Django 5.0 on 2023-12-19 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_combat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='gameid',
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='curTurn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='isSingle',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='lastTurn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='playerOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_states_as_player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='playerTwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_states_as_player_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
