# Generated by Django 5.0 on 2023-12-19 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_combat', '0002_remove_gamestate_gameid_alter_gamestate_curturn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipPositions', models.JSONField()),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sea_combat.gamestate')),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
