# Generated by Django 5.0 on 2023-12-20 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_combat', '0004_alter_boardstate_ownerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMoveHistory',
            fields=[
                ('gameState', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sea_combat.gamestate')),
                ('moveSequence', models.JSONField()),
            ],
        ),
    ]
