# Generated by Django 5.0 on 2023-12-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_combat', '0005_gamemovehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='curTurn',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='isPlayerOneTurn',
            field=models.BooleanField(default=True),
        ),
    ]
